package main;

import excepciones.Errores;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

public class Repoerrores extends javax.swing.JPanel {

    /**
     * Creates new form Repoerrores
     */
    LinkedList<Errores> listaErrores = new LinkedList<>();

    public Repoerrores(LinkedList<Errores> listaErrores) {
        this.listaErrores = listaErrores;
        initComponents();
        tablaErrores();
    }

    private void tablaErrores() {
        DefaultTableModel model = (DefaultTableModel) TB_errores.getModel();
        model.setRowCount(0);

        // Añadir cada error a la tabla
        for (Errores error : listaErrores) {
            model.addRow(new Object[]{
                error.getLexema(),
                error.getLinea(),
                error.getColumna(),
                error.getTipo(),
                error.getDesc()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TB_errores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        TB_errores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Lexema", "Linea", "Columna", "Tipo", "Descripcion"
            }
        ));
        jScrollPane1.setViewportView(TB_errores);
        if (TB_errores.getColumnModel().getColumnCount() > 0) {
            TB_errores.getColumnModel().getColumn(0).setMinWidth(150);
            TB_errores.getColumnModel().getColumn(0).setPreferredWidth(150);
            TB_errores.getColumnModel().getColumn(0).setMaxWidth(150);
            TB_errores.getColumnModel().getColumn(1).setMinWidth(100);
            TB_errores.getColumnModel().getColumn(1).setPreferredWidth(100);
            TB_errores.getColumnModel().getColumn(1).setMaxWidth(100);
            TB_errores.getColumnModel().getColumn(2).setMinWidth(100);
            TB_errores.getColumnModel().getColumn(2).setPreferredWidth(100);
            TB_errores.getColumnModel().getColumn(2).setMaxWidth(100);
            TB_errores.getColumnModel().getColumn(3).setMinWidth(150);
            TB_errores.getColumnModel().getColumn(3).setPreferredWidth(150);
            TB_errores.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        jLabel1.setFont(new java.awt.Font("FiraCode Nerd Font Mono", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reportes de Errores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 796, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 330, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TB_errores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
